trigger: none

variables:
  k8sNamespace: default

resources:
  pipelines:
  - pipeline: routefinal
    source: swm-route-final-build   # CI pipeline name
    trigger: none

stages:
- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - deployment: DeployJob
    displayName: AKS Deployment
    environment: aks-prod
    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:

          # 🔽 DOWNLOAD MANIFESTS FROM CI PIPELINE
          - task: DownloadPipelineArtifact@2
            displayName: Download Kubernetes Manifests
            inputs:
              source: pipeline
              pipeline: routefinal          # alias from resources
              artifact: manifests
              path: $(Pipeline.Workspace)/manifests

          # 🚀 DEPLOY TO AKS
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              connectionType: azureResourceManager
              azureSubscriptionConnection: agent-route-final-sc
              azureResourceGroup: rg-allvy-core-infra
              kubernetesCluster: allvy-apps-aks
              namespace: $(k8sNamespace)
              enableVariableSubstitution: true
              manifests: |
                $(Pipeline.Workspace)/manifests/manifests/secrets.yaml
                $(Pipeline.Workspace)/manifests/manifests/deployment.yaml
                $(Pipeline.Workspace)/manifests/manifests/service.yaml
