trigger: none

variables:
  k8sNamespace: default

stages:
- stage: Deploy
  displayName: Deploy to AKS
  jobs:
  - deployment: DeployJob
    displayName: AKS Deployment
    environment: aks-prod
    pool:
      vmImage: ubuntu-latest

    strategy:
      runOnce:
        deploy:
          steps:

          # 🔽 DOWNLOAD MANIFESTS (SPECIFIC PROJECT + PIPELINE)
          - task: DownloadPipelineArtifact@2
            displayName: Download Kubernetes Manifests
            inputs:
              source: specific
              project: SWM-ROUTE-FINAL        # 🔴 REQUIRED
              pipeline: swm-route-final-build
              runVersion: latest
              artifact: manifests
              path: $(System.DefaultWorkingDirectory)

          # 🚀 DEPLOY TO AKS
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              enableRolloutStatus: false
              connectionType: azureResourceManager
              azureSubscriptionConnection: agent-route-final-sc
              azureResourceGroup: rg-allvy-core-infra
              kubernetesCluster: allvy-apps-aks
              namespace: $(k8sNamespace)
              enableVariableSubstitution: true
              manifests: |
                $(System.DefaultWorkingDirectory)/service.yaml
                $(System.DefaultWorkingDirectory)/deployment.yaml
                $(System.DefaultWorkingDirectory)/secrets.yaml
