trigger:
- main

variables:
  ACR_NAME: allvysharedacr.azurecr.io
  IMAGE_NAME: swm-routing-agent

pool:
  vmImage: 'ubuntu-latest'

steps:

# 1 — Login to ACR
- task: DockerInstaller@0
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'ACR-ServiceConnection'

# 2 — Build image
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    repository: $(allvysharedacr.azurecr.io)/$(swm-routing-agent)
    dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

# 3 — Push image
- task: Docker@2
  displayName: Push Docker image
  inputs:
    command: push
    repository: $(allvysharedacr.azurecr.io)/$(swm-routing-agent)
    tags: |
      $(Build.BuildId)

# 4 — Set AKS kubeconfig
- task: AzureCLI@2
  displayName: Login to AKS
  inputs:
    azureSubscription: 'AKS-ServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -g <RESOURCE_GROUP> -n <AKS_CLUSTER> --overwrite-existing

# 5 — Apply manifests
- task: Kubernetes@1
  displayName: Deploy to AKS
  inputs:
    connectionType: 'None'
    command: apply
    useConfigurationFile: True
    configuration: |
      manifests/deployment.yaml
      manifests/service.yaml
      manifests/ingress.yaml
      manifests/hpa.yaml
